export const labels = {
  adminPanel: "Panel",
  availableSpots: "Dostępne miejsca: ",
  assignedTo: "Zapisani na",
  doesntHaveAccount: "Nie masz konta?",
  email: "Email",
  homePage: "Strona główna",
  freeSpot: "Wypisz się",
  logIn: "Zaloguj",
  myReservations: "Moje rezerwacje",
  noAssignmentsYet: "Nikt się jeszcze nie zapisał",
  noTrainingsOnThatDate: "Tego dnia nie ma treningów",
  password: "Hasło",
  register: "Zarejestruj się.",
  registerButton: "Zarejestruj",
  repeatPassword: "Powtórz hasło",
  reserve: "Rezerwuj",
  reserveSpot: "Zapisz mnie",
  selectTrainingDay: "Wybierz dzień",
  selectTraining: "Wybierz trening",
  signInToReservSpot: "Zaloguj się, żeby zarezerwować miejsce",
  signIn: "Zaloguj się",
  signOut: "Wyloguj",
  userName: "Nazwa użytkownika",
  youAreNotAssignedYet: "Nie masz zarezerwowanych treningów",
};

export const apiLabels = {
  alreadyAssignedToThatTraining: "Jesteś już zapisany/a na ten trening",
  checkEmail: "Sprawdź email",
  didntFreeSpot: "Nie udało się wypisać z treningu",
  didntReserveSpot: "Nie udało się zapisać na ten trening",
  noSpotsLeftOnThatTraining: "Nie ma już wolnych miejsc na tym treningu",
  passwordToWeak: "Hasło musi mieć > 6 znaków",
  selectTraining: "Wybierz trening",
  somethingWentWrong: "Coś poszło nie tak",
  spotReserved: "Zapisano na trening",
  spotFreed: "Wypisano z treningu",
  userDoesntExist: "Taki użytkownik nie istnieje",
  userAlreadyExists: "Podany email już istnieje",
  wrongPassword: "Wpisane hasło jest nieprawidłowe",
};

export const validationLabels = {
  thisFieldIsRequired: "To pole jest wymagane",
  thisFieldMustBeAnEmail: "Wpisz poprawny email",
  mustBeAtLeast: "musi mieć minimum",
  passwordChars: "znaków",
  passwordsMustMatch: "Hasła muszą pasować",
};
